# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name : girrajahentpool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd "$(Build.SourcesDirectory)\Dev-Enviroment\Azurerm-Child-Moduls\Azurerm-Resource-Group"
      # Write your PowerShell commands here.
      
      terraform init
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(System.DefaultWorkingDirectory)"\Dev-Enviroment\Azurerm-Child-Moduls\Azurerm-Resource-Group"
    environmentServiceNameAzureRM: 'girraj-svc'
